# @package _global_
model:
  charset_train: " ৗ ূ ৌ ু ী ি ঃ ং ো ্ ৃ ঁ া ় ৈ ে ৄ ৢ ৣতউঝকঐথঞখণঘনঔপ৩ৠ৮ফঌঊছওভষদঙৱইড৫ৎব৹২৷৪অটএজঽৰহশরধঈচআম০৳ঠ৺৭ঋগ৬৯ৡ১সঢযল৲য়৸৻ঀ৴৵৶ড়ঢ় "
  charset_test: " ৗ ূ ৌ ু ী ি ঃ ং ো ্ ৃ ঁ া ় ৈ ে ৄ ৢ ৣতউঝকঐথঞখণঘনঔপ৩ৠ৮ফঌঊছওভষদঙৱইড৫ৎব৹২৷৪অটএজঽৰহশরধঈচআম০৳ঠ৺৭ঋগ৬৯ৡ১সঢযল৲য়৸৻ঀ৴৵৶ড়ঢ় "
